### ISSUE TITLE
Tracking porting the commands parser to the tree-sitter-based one

### ISSUE THREAD

**Issue by XVilka** [rizinorg/rizin#1342]
# Finished porting

- [x] `!` (external commands) - https://github.com/rizinorg/rizin/pull/1235
- [x] `i` (information) https://github.com/rizinorg/rizin/pull/1238
- [x] `b` (block size) https://github.com/rizinorg/rizin/pull/1745
- [x] `r` (resize) https://github.com/rizinorg/rizin/pull/1737
- [x] `y` (yank) https://github.com/rizinorg/rizin/pull/1734
- [x]  `g` (shellcodes) https://github.com/rizinorg/rizin/pull/1744
- [x] `c` (compare) https://github.com/rizinorg/rizin/pull/1854
- [x] `C` (meta information) https://github.com/rizinorg/rizin/pull/1752
- [x] `f` (flags) #1587 https://github.com/rizinorg/rizin/pull/2211
- [x] `m` (magic) #1588
- [x] `-` (open editor) #1585
- [x] `o` (open) #1589
- [x] #2363
- [x] #1584
- [x] #2834
- [x] #1583
- [x] `ae` (analysis) - https://github.com/rizinorg/rizin/issues/1533
- [x] `k` (query) - not sure if necessary as is since many parts migrated from SDB to hashtables. On the other hand, a hashtable-based query feature would also be useful.
- [x]  `d` (debug)
- [x] `p` (print) - mostly done, only `px/` left, blocked on search (`/`) commands porting first: #1590
- [x] `R` (remote) - partially ported, missing `Rg`, `Rh`, `RH`, `R!`
- [x] `x` (hexdump) - alias for `px`

# Unfinished

- [x] #1586

**Comment by ret2libc** [comment]
>  0 (alias for s 0x...) - actually not sure if it's better to remove it completely

I propose to remove this. @XVilka @ITAYC0HEN @thestr4ng3r @wargio @kazarmy

**Comment by wargio** [comment]
yes, is better to uniform

**Comment by thestr4ng3r** [comment]
remove
