### ISSUE TITLE
Add Trans theory and rounding modes into RZIL

### ISSUE THREAD

**Issue by XVilka** [rizinorg/rizin#1461]
Currently only supported theories are:
- Bool
- Bitvector
- Mem (Array)
- Effect

The biggest missing chunk is the Float theory

- [x] Implement IEE754 types and helper APIs in RzUtil
- [x] Implement Fbasic operations https://github.com/rizinorg/rizin/pull/3184
- [x] Cover these by unit tests
- [ ] Add rounding modes (Rmode) operations
- [ ] Add Trans (transcendental) operations

See:
- http://binaryanalysisplatform.github.io/bap/api/odoc/bap-core-theory/Bap_core_theory/Theory/Float/index.html
- http://binaryanalysisplatform.github.io/bap/api/odoc/bap-core-theory/Bap_core_theory/Theory/Rmode/index.html
- http://binaryanalysisplatform.github.io/bap/api/odoc/bap-core-theory/Bap_core_theory/Theory/module-type-Fbasic/index.html
- http://binaryanalysisplatform.github.io/bap/api/odoc/bap-core-theory/Bap_core_theory/Theory/module-type-Float/index.html
- http://binaryanalysisplatform.github.io/bap/api/odoc/bap-core-theory/Bap_core_theory/Theory/module-type-Trans/index.html
- http://binaryanalysisplatform.github.io/bap/api/odoc/bap-core-theory/Bap_core_theory/Theory/IEEE754/index.html

Implementation is at https://github.com/BinaryAnalysisPlatform/bap/blob/master/lib/bap_core_theory/bap_core_theory_definition.ml

Note, I think that **Trans** theory should be separate from the **Float** in the code.

http://binaryanalysisplatform.github.io/bap/api/odoc/bap-core-theory/Bap_core_theory/Theory/module-type-Core/index.html

**Comment by XVilka** [comment]
Better description of the rounding modes is here: http://binaryanalysisplatform.github.io/bap/api/master/bap-core-theory/Bap_core_theory/Theory/module-type-Float/index.html#rounding-modes

@brightprogrammer @Heersin @imbillow

**Comment by Rot127** [comment]
The current float operations don't support dynamic rounding mode selection. They must be static. This needs refactoring, because most architectures select the rounding mode via some flags in a float status register.
(I assume this is what you meant with "Add rounding modes (Rmode) operations" as well?)

**Comment by notxvilka** [comment]
>  (I assume this is what you meant with "Add rounding modes (Rmode) operations" as well?)

Precisely.

**Comment by Heersin** [comment]
> The current float operations don't support dynamic rounding mode selection. They must be static. This needs refactoring, because most architectures select the rounding mode via some flags in a float status register. (I assume this is what you meant with "Add rounding modes (Rmode) operations" as well?)

yes, dynamic routing should be supported unless float support runtime rmode detection.
