### ISSUE TITLE
Not all unit test requiring install accept the RZ_PREFIX env var

### ISSUE THREAD

**Issue by thestr4ng3r** [rizinorg/rizin#1789]
Especially for distribution packaging, it is often useful to run all unit tests without installing, or with the install staged into a temporary directory.
The `RZ_PREFIX` env var can be used to tell the tests where the prefix is, but tests taking the prefix directly from `rz_sys_env()` will not respect that.
This makes patching like this necessary: https://paste.sr.ht/~thestr4ng3r/89fb2703bb74a8463d2d97d9c9cf240325ef706b

~~We could either:~~
* ~~Make `rz_sys_prefix()` also read the environment (maybe not so nice to have such logic in util/sys)~~
* ~~Add a unit-test specific function that returns `getenv("RZ_PREFIX") ? getenv("RZ_PREFIX") : rz_sys_prefix(NULL)`~~

Concrete plan to implement this, as discussed below:

- [ ] Add a function that generates the prefix by respecting `RZ_PREFIX` and others, as a heap-allocated local string, without setting any global state, in an appropriate place.
- [ ] Remove direct uses of rz_sys_prefix and similar functions (e.g. rz_str_rz_prefix) from all Rz modules
- [ ] Inject the prefix from the constructor, see https://github.com/rizinorg/rizin/issues/1789#issuecomment-933304576
- [ ] Change unit tests to make use of the function described above
- [ ] Move tests depending on rizin-testbins to integration-tests.

**Comment by ret2libc** [comment]
> Add a unit-test specific function that returns getenv("RZ_PREFIX") ? getenv("RZ_PREFIX") : rz_sys_prefix(NULL)

I'd go for this!

That said, is that going to be enough to make tests runnable without installing? Also, many unit tests require rizin-testbins to run, which is not really "unit" and i'm not sure many distros would like to download all those things (what about licenses as well?) just to run few unit tests.

**Comment by thestr4ng3r** [comment]
Another possibility would be to have a function that always "calculates" the prefix and returns an alloced string (`RZ_OWN char 
*rz_core_calculate_prefix(RZ_NULLABLE RzCore *core)`, core optional) which can be used in the unit tests and freed there as well. RzCore can call it once and save the prefix to avoid later recalculation. Then `rz_sys_prefix()` can be removed from util entirely.

> That said, is that going to be enough to make tests runnable without installing?

Definitely not, the gentoo one for example sets up a fake-prefix with some symlinks into src/build dirs.

> Also, many unit tests require rizin-testbins to run, which is not really "unit" and i'm not sure many distros would like to download all those things (what about licenses as well?) just to run few unit tests.

Maybe those could all be moved to the C integration tests.

**Comment by ret2libc** [comment]
The thing is that rz_sys_prefix and other functions are called from multiple places that are dependencies of RzCore, so you can't put that into RzCore itself.

**Comment by thestr4ng3r** [comment]
It could be injected from outside, e.g. like https://github.com/rizinorg/rizin/blob/e75fbc55516a3585c81bd6bd80c526bd8a5d7f6d/librz/include/rz_type.h#L237

**Comment by ret2libc** [comment]
That seems like a good idea indeed. However there are cases like rz-bin where a RzCore is not available but you'd still want to access the Rizin Prefix. Shall we duplicate the code there? :(

**Comment by thestr4ng3r** [comment]
Hmm yeah that sucks. I guess the generator function could still be kept in util, even if that's not super nice.

**Comment by ret2libc** [comment]
So, to rephrase the issue:
- [ ] Remove direct uses of rz_sys_prefix and similar functions (e.g. rz_str_rz_prefix) from all Rz modules
- [ ] Inject the prefix from the constructor, see https://github.com/rizinorg/rizin/issues/1789#issuecomment-933304576
- [ ] Change unit tests to have the injected prefix respect RZ_PREFIX env var first
- [ ] Move tests depending on rizin-testbins to integration-tests.

Does that sound alright?

**Comment by thestr4ng3r** [comment]
I would say:

- [ ] Add a function that generates the prefix by respecting `RZ_PREFIX` and others, as a heap-allocated local string, without setting any global state, in an appropriate place.
- [ ] Remove direct uses of rz_sys_prefix and similar functions (e.g. rz_str_rz_prefix) from all Rz modules
- [ ] Inject the prefix from the constructor, see https://github.com/rizinorg/rizin/issues/1789#issuecomment-933304576
- [ ] Change unit tests to make use of the function described above
- [ ] Move tests depending on rizin-testbins to integration-tests.

That is, modulo any issues that come up while implementin this.

**Comment by ret2libc** [comment]
> Add a function that generates the prefix by respecting RZ_PREFIX and others, as a heap-allocated local string, without setting any global state, in an appropriate place.

I'm ok with all other points. For this, I was thinking about the Portable builds, which find important resources based on the rizin prefix.. Is it safe to allow the external env to change this? Probably it is, but just thinking...

**Comment by thestr4ng3r** [comment]
I would say yes, since in core that already happens. The only danger is of course that one may have `RZ_PREFIX` set to something globally and forget about it, causing another build to do weird things. But it wouldn't be a regression at least.

**Comment by ret2libc** [comment]
Sounds good. Please update the description of the issue so it's clear what to do in case some newcomers want to pick this up.

**Comment by ajakk** [comment]
> This issue has been automatically marked as stale because it has not had recent activity. Considering a lot has probably changed since its creation, we kindly ask you to check again if the issue you reported is still relevant in the current version of rizin. If it is, update this issue with a comment, otherwise it will be automatically closed if no further activity occurs. Thank you for your contributions.

There's only been four minor releases, and distros (well, at least Gentoo) is still hacking around the issue.
