### ISSUE TITLE
Release 0.6.0 checklist

### ISSUE THREAD

**Issue by XVilka** [rizinorg/rizin#3720]
# Release checklist template

For each new Rizin release create a new issue on GitHub with this file as its
content. Go step-by-step through it.

- [x] Update `stable` branch in the proper way
  - [x] Merge `dev` branch into `stable` branch (for major updates). See https://github.com/rizinorg/rizin/blob/dev/doc/RELEASE.md#majorminor-release.
  - [x] Cherry-pick relevant commits from `dev` branch into `stable` branch (for patch updates or once `stable` and `dev` have already diverged considerably). See https://github.com/rizinorg/rizin/blob/dev/doc/RELEASE.md#patch-release.
  - [x] Update `version` field in [`meson.build`](https://github.com/rizinorg/rizin/blob/dev/meson.build) file.
- [x] Submit a PR of `stable` branch against `origin/stable`. If you have push access to origin, you should create another branch with a different name and submit anyway a PR for others to review.
- [x] Ensure that CI on `stable` branch is all green. If not, fix issues and iterate previous steps as necessary.
- [x] Merge PR so that `origin/stable` is updated with the new content.
- [x] Manually test that things work well, in particular major changes in the new release.
- [x] Start preparing release notes by modifying the draft release automatically created by GitHub CI.
- [x] Check that [Cutter](https://github.com/rizinorg/cutter) works well with the new version of Rizin. If not, fix as necessary and go back to previous steps until everything is ready. Cutter and Rizin should be released at the same time, so both should be in a good state with major issues solved.
  - [x] Cutter can be compiled with new version of Rizin.
  - [x] Basic Cutter functions work well with new version of Rizin.
  - [x] Cutter is in good shape to be released.
- [x] Check that [rz-ghidra](https://github.com/rizinorg/rz-ghidra) works well with the new version of Rizin. If not, fix as necessary and go back to previous steps until everything is ready.
- [x] Check that [jsdec](https://github.com/rizinorg/jsdec) works well with the new version of Rizin. If not, fix as necessary and go back to previous steps until everything is ready.
- [x] Check that [rz-retdec](https://github.com/rizinorg/rz-retdec) works well with the new version of Rizin. If not, fix as necessary and go back to previous steps until everything is ready.
- [x] Check that [rizin-extras](https://github.com/rizinorg/rizin-extras/) and rz-keystone in particular works well with the new version of Rizin. If not, fix as necessary and go back to previous steps until everything is ready.
- [x] Check that core plugins in [rz-pm-db](https://github.com/rizinorg/rz-pm-db) can be installed correctly with the new version of Rizin. If not, fix as necessary and go back to previous steps until everything is ready.
- [x] Replace `RZ_PIPE_PY_VERSION` and `RZ_GHIDRA_VERSION` in [`Dockerfile`](https://github.com/rizinorg/rizin/blob/dev/Dockerfile) with the right commits from those repositories. Merge the commit with the Rizin changes in the `stable` branch.
- [x] Quick test again that Rizin and Cutter work together.
- [x] Finalize release notes.
- [x] Release Rizin and Cutter by making their release public on GitHub.
- [x] Tag rz-pipe for the new version.
- [x] Tag [rz-bindgen](https://github.com/rizinorg/rz-bindgen) for the new version.
- [x] Tag rz-ghidra for the new version.
- [x] Tag rz-keystone/rizin-extras for the new version.
- [x] Tag jsdec for the new version.
- [x] Tag rz-retdec for the new version.

**Comment by ret2libc** [comment]
Everything is done!
