### ISSUE TITLE
MIPS: updating capstone and RzIL

### ISSUE THREAD

**Issue by XVilka** [rizinorg/rizin#4007]
- [x] Update capstone using auto-sync to support all MIPS instructions: https://github.com/capstone-engine/capstone/pull/2410 https://github.com/rizinorg/rizin/issues/3684
- [x] merge `librz/analysis/p/analysis_mips.c` into `librz/analysis/p/analysis_mips_cs.c` and remove the dependency on binutils code https://github.com/rizinorg/rizin/pull/4621
- [x] Convert analysis plugin for MIPS to RzIL: https://github.com/rizinorg/rizin/issues/2080 and https://github.com/rizinorg/rizin/pull/3508
- [ ] Support for floating point instructions in RzIL for MIPS: https://github.com/rizinorg/rizin/issues/3529
- [ ] Add more tests, e.g. https://github.com/rizinorg/rizin-testbins/issues/128
- [x] DWARF register profile for MIPS targets: https://github.com/rizinorg/rizin/issues/3699
- [x] Octeon instructions, see https://github.com/Vector35/binaryninja-api/pull/5615

**Comment by notxvilka** [comment]
Substituted by https://github.com/rizinorg/rizin/issues/5202
