### ISSUE TITLE
[RzArch] Progress tracker

### ISSUE THREAD

**Issue by Rot127** [rizinorg/rizin#4334]
## Tracking issue for `RzArch`

**Refactor old plugin**

- [x] Merge `asm` and `analysis`
  - [x] Merge `asm` and `analysis` code (keep plugin structure) (https://github.com/rizinorg/rizin/pull/4332)
  - [x] Mark `asm`/`analysis` plugin API as deprecated.
  - [ ] Rename existing `rz_arch_` functions to something else.
- [x] Move pseudo code generator code from `RzParse` into the merged `asm`/`analysis` directories.

**Extensions and new `RzArch` plugin**

- [ ] Add new `RzArch` plugin (see: https://github.com/rizinorg/rizin/pull/2557)
- [ ] Add compatibility functions (since we need to support `asm`/`analysis`/`arch` for a while all at once):
  - [ ] Wrap old `RzAnalysis` and `RzAsm` API functions into some new functions. They should check if the plugin is a `RzArch` plugin and call the new API if yes.
  - [ ] If `RzArch` returns different objects/data/values whatever, translate them for `core` 
- [ ] Refactor each archs `asm` and `analysis` plugin into the new `RzArch` plugin
  - [ ] `6502`
  - [ ] `8051`
  - [ ] `amd29k`
  - [ ] `arc`
  - [ ] `arm`
  - [ ] `avr`
  - [ ] `cil`
  - [ ] `cr16`
  - [ ] `cris`
  - [ ] `dalvik`
  - [ ] `dcpu16`
  - [ ] `ebc`
  - [ ] `gb`
  - [ ] `h8300`
  - [ ] `hexagon`
  - [ ] `hppa`
  - [ ] `i4004`
  - [ ] `i8080`
  - [ ] `include`
  - [ ] `java`
  - [ ] `lanai`
  - [ ] `lh5801`
  - [ ] `lm32`
  - [ ] `luac`
  - [ ] `mcore`
  - [ ] `mcs96`
  - [ ] `mips`
  - [ ] `msp430`
  - [ ] `nios`
  - [ ] `or1k`
  - [ ] `pic`
  - [ ] `ppc`
  - [ ] `propeller`
  - [ ] `pyc`
  - [ ] `riscv`
  - [ ] `rl78`
  - [ ] `rsp`
  - [ ] `rx`
  - [ ] `sh`
  - [ ] `snes`
  - [ ] `sparc`
  - [ ] `spc700`
  - [ ] `tms320`
  - [ ] `tricore`
  - [ ] `v810`
  - [ ] `v850`
  - [ ] `vax`
  - [ ] `wasm`
  - [ ] `xap`
  - [ ] `xtensa`
  - [ ] `z80`
- [ ] Refactor bindings generation (`rz-bindgen`)
- [ ] Refactor external plugins
  - [ ] `rz-ghidra`
  - [ ] `jsdec`
  - [ ] rizin-extras
  - [ ] Cutter
- [ ] Move certain APIs to own plugins:
  - [ ] (?) https://github.com/rizinorg/rizin/pull/4306
- [ ] Remove compatibility code and make `core` use only the new `RzArch` API.
- [ ] Update code documentation and book
- [ ] Others
  - [ ] Address https://github.com/rizinorg/rizin/blob/fb6efca4b54d5455a1d7ec30ce0ec868ef3ddcad/librz/arch/isa/hexagon/hexagon_il.c#L243-L247
