### ISSUE TITLE
Xtensa - Plugin improvements

### ISSUE THREAD

**Issue by XVilka** [rizinorg/rizin#4383]
Currently Xtensa support is pretty basic and is based on the binutils code.

- [x] Implement Xtensa in Capstone: https://github.com/capstone-engine/capstone/issues/2015
- [x] Port Xtensa plugin to the new capstone-based one https://github.com/rizinorg/rizin/pull/4654
- [x] Port Xtensa plugin from ESIL to RzIL: https://github.com/rizinorg/rizin/issues/2080
- [x] Add more file-based tests
- [ ] Implement FLIX? https://github.com/NationalSecurityAgency/ghidra/issues/6342
- [ ] Support XTensa in rz-ghidra: https://github.com/rizinorg/rz-ghidra/issues/351

**Comment by ashiskumarnaik** [comment]
@XVilka please assign this

**Comment by Rot127** [comment]
Done. Does this mean you would also like to implement the Capstone module?
In this case please let me know. I can/should give you some guidance for this.

**Comment by Rot127** [comment]
@DanielAW As far as I am aware of, you are the only one who did recently public work on Xtensa based firmware. Was there any quality of live improvements you wished to have, when working on it with other RE frameworks (besides the `LITBASE` problem you mentioned in your [talk](https://www.youtube.com/watch?v=QMO2vMBcx7Y))?
Adding your remarks to the list above, would be of great value.
