### ISSUE TITLE
Tracker: Finish up commands port to RzShell

### ISSUE THREAD

**Issue by Rot127** [rizinorg/rizin#4738]
Last not-RzShell commands.
After those are removed, `RZ_CMD_DESC_TYPE_OLDINPUT` is no where used anymore.

### Debugging

- [x] `dmhb`
- [x] `dmhf`
- [x] `dcu`
- [x] `dta`
- [x] `dmi`
- [x] `dmx`
- [x] https://github.com/rizinorg/rizin/pull/4753
- [ ] https://github.com/rizinorg/rizin/issues/3842

### sdb query

- [x] `k` - https://github.com/rizinorg/rizin/pull/4747

### Bin object

- [x] `ik` - https://github.com/rizinorg/rizin/pull/4750
- [ ] https://github.com/rizinorg/rizin/issues/1475

### remote - https://github.com/rizinorg/rizin/pull/4957

- [x] `R!`
- [x] `Rg`
- [x] `Rh`
- [x] `RH`

### Visual mode

- [x] `v` - https://github.com/rizinorg/rizin/pull/4745
- [x] `V` - https://github.com/rizinorg/rizin/pull/4745

### Printing https://github.com/rizinorg/rizin/issues/1590
- [x] `pj` - https://github.com/rizinorg/rizin/pull/4726
- [x] `px/` - https://github.com/rizinorg/rizin/pull/4961
- [x] `x` - https://github.com/rizinorg/rizin/pull/4969

### Search

- [x] `s/`
- [x] Complete refactor: https://github.com/rizinorg/rizin/issues/1586 and https://github.com/rizinorg/rizin/pull/4742

### ESIL emu

- [x] `ae...` - https://github.com/rizinorg/rizin/pull/4732

### Internal command calling

- [ ] https://github.com/rizinorg/rizin/pull/4339
